// apps/web/src/routes/world/schemas/create/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import {
    ArrowLeft,
    Check,
    Plus,
    Trash2,
    Layers,
    Boxes,
    Calculator,
    Link2,
    ListFilter,
    Hash,
    Type,
    ToggleLeft,
    Sparkles,
    AlertCircle,
    Info,
  } from 'lucide-svelte';
  import Button from '$lib/components/ui/button.svelte';
  import Input from '$lib/components/ui/input.svelte';
  import Select from '$lib/components/ui/select.svelte';
  import Label from '$lib/components/ui/label.svelte';
  import Field from '$lib/components/ui/field.svelte';
  import Textarea from '$lib/components/ui/textarea.svelte';
  import Breadcrumb from '$lib/components/ui/breadcrumb.svelte';
  import {
    worldStore,
    type BlueprintClass,
    type BlueprintFieldType,
    type DynamicFieldDef,
  } from '$lib/stores/worldStore.svelte';
  import {
    evaluateFormula,
    extractFormulaVariables,
    validateFormulaSyntax,
  } from '$lib/engine/formulaEngine';

  let name = $state('');
  let blueprintClass = $state<BlueprintClass>('FIRST_CLASS');
  let category = $state('Characters');
  let description = $state('');

  // Draft fields list
  // Draft fields list
  let fields = $state<Array<{
    id: string;
    name: string;
    label: string;
    fieldType: BlueprintFieldType;
    description: string;
    options: Array<{ label: string; value: string; power?: number; numericValue?: number }>;
    newOptionLabel: string;
    newOptionPower: number | undefined;
    targetBlueprintId: string;
    min: number;
    max: number;
    step: number;
    unit: string;
    defaultValue: string;
    formulaExpression: string;
  }>>([
    {
      id: 'f-1',
      name: 'gender',
      label: 'Gender Identity',
      fieldType: 'ENUM',
      description: 'Biological / spiritual gender category',
      options: [
        { label: 'Male', value: 'Male', power: 0, numericValue: 0 },
        { label: 'Female', value: 'Female', power: 0, numericValue: 0 },
        { label: 'Dual-Yin-Yang', value: 'Dual-Yin-Yang', power: 50, numericValue: 50 },
        { label: 'Celestial / Genderless', value: 'Celestial / Genderless', power: 100, numericValue: 100 },
      ],
      newOptionLabel: '',
      newOptionPower: undefined,
      targetBlueprintId: '',
      min: 0,
      max: 100,
      step: 1,
      unit: '',
      defaultValue: 'Male',
      formulaExpression: '',
    },
  ]);

  // Quick categories
  const suggestedCategories = [
    'Characters',
    'Relics & Armaments',
    'Cosmology & Geography',
    'Sects & Factions',
    'Systems & Affection',
    'Power Systems',
  ];

  const fieldTypeOptions = [
    { value: 'STRING', label: 'Text (String)' },
    { value: 'NUMBER', label: 'Number (Numeric with bounds)' },
    { value: 'ENUM', label: 'Enum / Custom Categories (Options with Power/Value)' },
    { value: 'BLUEPRINT_REF', label: 'Blueprint Reference (1st or 2nd Class)' },
    { value: 'FORMULA', label: 'Formula (Mathematical & Logical Computed Math)' },
    { value: 'BOOLEAN', label: 'Toggle (Boolean)' },
  ];

  // Available blueprints for referencing
  let availableTargetBlueprints = $derived(
    worldStore.blueprints.map((bp) => ({
      value: bp.id,
      label: `${bp.name} (${bp.blueprintClass === 'FIRST_CLASS' ? '1st Class' : '2nd Class'} · ${bp.category})`,
    }))
  );

  function addField() {
    fields.push({
      id: `draft-f-${Date.now()}-${Math.random().toString(16).substring(2, 6)}`,
      name: '',
      label: '',
      fieldType: 'STRING',
      description: '',
      options: [],
      newOptionLabel: '',
      newOptionPower: undefined,
      targetBlueprintId: availableTargetBlueprints[0]?.value || '',
      min: 0,
      max: 100000,
      step: 1,
      unit: '',
      defaultValue: '',
      formulaExpression: '',
    });
  }

  function removeField(index: number) {
    fields.splice(index, 1);
  }

  function addOptionToField(fieldIndex: number) {
    const label = fields[fieldIndex].newOptionLabel.trim();
    if (!label) return;
    const power = fields[fieldIndex].newOptionPower;
    const value = label.toLowerCase().replace(/\s+/g, '_');
    
    fields[fieldIndex].options.push({
      label,
      value,
      power: power !== undefined ? Number(power) : 0,
      numericValue: power !== undefined ? Number(power) : 0,
    });

    if (!fields[fieldIndex].defaultValue) {
      fields[fieldIndex].defaultValue = value;
    }

    fields[fieldIndex].newOptionLabel = '';
    fields[fieldIndex].newOptionPower = undefined;
  }

  function removeOptionFromField(fieldIndex: number, optionIndex: number) {
    fields[fieldIndex].options.splice(optionIndex, 1);
  }

  function insertTokenIntoFormula(fieldIndex: number, token: string) {
    const current = fields[fieldIndex].formulaExpression;
    fields[fieldIndex].formulaExpression = current ? `${current} ${token}` : token;
  }

  // Live formula test evaluation
  function getFormulaValidation(expr: string) {
    if (!expr) return { valid: false, error: 'Empty formula expression' };
    return validateFormulaSyntax(expr);
  }

  function handleCreateBlueprint() {
    if (!name.trim()) {
      alert('Blueprint name is required.');
      return;
    }

    // Build valid DynamicFieldDef items
    const validFields: DynamicFieldDef[] = fields
      .filter((f) => f.name.trim() !== '' || f.label.trim() !== '')
      .map((f, idx) => {
        const fieldKey = (f.name.trim() || f.label.trim().toLowerCase().replace(/\s+/g, '_')).replace(/[^a-zA-Z0-9_\.]/g, '');
        const def: DynamicFieldDef = {
          id: `f-${Date.now()}-${idx}`,
          name: fieldKey,
          label: f.label.trim() || fieldKey,
          fieldType: f.fieldType,
          description: f.description.trim(),
        };

        if (f.fieldType === 'ENUM') {
          def.options = f.options.length > 0 ? [...f.options] : ['Default'];
          def.defaultValue = f.defaultValue || def.options[0];
        } else if (f.fieldType === 'NUMBER') {
          def.min = f.min;
          def.max = f.max;
          def.step = f.step;
          def.unit = f.unit;
          def.defaultValue = parseFloat(f.defaultValue) || 0;
        } else if (f.fieldType === 'BLUEPRINT_REF') {
          def.targetBlueprintId = f.targetBlueprintId;
          const targetBp = worldStore.getBlueprint(f.targetBlueprintId);
          def.targetBlueprintName = targetBp?.name;
        } else if (f.fieldType === 'FORMULA') {
          def.formulaExpression = f.formulaExpression.trim();
          def.formulaDependencies = extractFormulaVariables(f.formulaExpression);
        } else if (f.fieldType === 'BOOLEAN') {
          def.defaultValue = f.defaultValue === 'true';
        } else {
          def.defaultValue = f.defaultValue;
        }

        return def;
      });

    worldStore.addBlueprint({
      name: name.trim(),
      blueprintClass,
      category: category.trim() || 'General',
      description: description.trim(),
      fields: validFields,
    });

    goto('/world/schemas');
  }
</script>

<div class="max-w-4xl mx-auto space-y-6 pb-16">
  <!-- Breadcrumb -->
  <Breadcrumb
    items={[
      { label: 'World Studio', href: '/world' },
      { label: 'Blueprints & Schemas', href: '/world/schemas' },
      { label: 'Create Blueprint from Scratch' },
    ]}
  />

  <!-- Header -->
  <div class="flex items-center justify-between border-b border-zinc-800 pb-4">
    <div>
      <h2 class="text-xl font-bold tracking-tight text-zinc-100 flex items-center gap-2">
        <Boxes class="w-5 h-5 text-teal-400" />
        <span>Create Blueprint from Scratch</span>
      </h2>
      <p class="text-xs text-zinc-400 mt-1">
        Define custom 1st-Class Entity archetypes or 2nd-Class sub-blueprints with dynamic enums, blueprint references, and mathematical formulas.
      </p>
    </div>
    <a href="/world/schemas">
      <Button variant="outline" size="sm">
        <ArrowLeft class="w-3.5 h-3.5" />
        <span>Back to Blueprints</span>
      </Button>
    </a>
  </div>

  <!-- Blueprint Meta Config -->
  <div class="bg-zinc-900 rounded-lg border border-zinc-800 p-6 space-y-5">
    <h3 class="text-xs font-semibold text-zinc-300 uppercase tracking-wider flex items-center gap-2">
      <Layers class="w-4 h-4 text-teal-400" />
      <span>Blueprint Classification & Category</span>
    </h3>

    <!-- Blueprint Class Selector -->
    <div>
      <span class="block text-xs font-medium text-zinc-400 mb-2">Blueprint Tier / Class</span>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
        <button
          type="button"
          onclick={() => (blueprintClass = 'FIRST_CLASS')}
          class={`p-4 rounded-lg border text-left transition flex flex-col justify-between ${
            blueprintClass === 'FIRST_CLASS'
              ? 'border-teal-500 bg-teal-950/30 ring-1 ring-teal-500/50'
              : 'border-zinc-800 bg-zinc-950/50 hover:border-zinc-700'
          }`}
        >
          <div>
            <div class="flex items-center gap-2 text-zinc-100 font-semibold text-sm">
              <Boxes class="w-4 h-4 text-teal-400" />
              <span>1st-Class Blueprint (Primary Entity Archetype)</span>
            </div>
            <p class="text-xs text-zinc-400 mt-1.5 leading-relaxed">
              Instantiates tangible universe entities (e.g. Cultivator Characters, Divine Relics, Factions, Sects, Realms) with timeline lifecycles and causal mutations.
            </p>
          </div>
          <div class="mt-3 text-[11px] text-teal-400 font-medium">Instantiable in Universe Timeline</div>
        </button>

        <button
          type="button"
          onclick={() => (blueprintClass = 'SECOND_CLASS')}
          class={`p-4 rounded-lg border text-left transition flex flex-col justify-between ${
            blueprintClass === 'SECOND_CLASS'
              ? 'border-cyan-500 bg-cyan-950/30 ring-1 ring-cyan-500/50'
              : 'border-zinc-800 bg-zinc-950/50 hover:border-zinc-700'
          }`}
        >
          <div>
            <div class="flex items-center gap-2 text-zinc-100 font-semibold text-sm">
              <Layers class="w-4 h-4 text-cyan-400" />
              <span>2nd-Class Blueprint (Sub-Schema & Value Object)</span>
            </div>
            <p class="text-xs text-zinc-400 mt-1.5 leading-relaxed">
              Reusable nested sub-schemas, gauges, or matrices (e.g. Romantic Affection Scale, Cultivation Mastery Matrix, Elemental Roots) referenced inside 1st-Class blueprints.
            </p>
          </div>
          <div class="mt-3 text-[11px] text-cyan-400 font-medium">Embeddable & Referenceable Schema</div>
        </button>
      </div>
    </div>

    <!-- Name & Freeform Category -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <Field id="bp-name" label="Blueprint Name" required>
        <Input
          id="bp-name"
          bind:value={name}
          placeholder="e.g. Divine Beast, Sect Patriarch, Romantic Affection Scale"
          class="w-full"
        />
      </Field>

      <Field id="bp-cat" label="Category / Domain (Free-form)">
        <Input
          id="bp-cat"
          bind:value={category}
          placeholder="e.g. Characters, Relics, Systems & Affection"
          class="w-full"
        />
        <!-- Quick Suggestions -->
        <div class="flex flex-wrap gap-1.5 mt-2">
          {#each suggestedCategories as sug}
            <button
              type="button"
              onclick={() => (category = sug)}
              class="text-[10px] px-2 py-0.5 rounded bg-zinc-800 text-zinc-400 hover:text-zinc-200 hover:bg-zinc-700 transition"
            >
              {sug}
            </button>
          {/each}
        </div>
      </Field>
    </div>

    <Field id="bp-desc" label="Description & Lore Scope">
      <Textarea
        id="bp-desc"
        bind:value={description}
        rows={2}
        placeholder="Describe the archetypal purpose and mechanics governed by this blueprint..."
        class="w-full text-xs"
      />
    </Field>
  </div>

  <!-- Dynamic Field Builder -->
  <div class="bg-zinc-900 rounded-lg border border-zinc-800 p-6 space-y-6">
    <div class="flex items-center justify-between border-b border-zinc-800 pb-3">
      <div>
        <h3 class="text-xs font-semibold text-zinc-300 uppercase tracking-wider flex items-center gap-2">
          <Sparkles class="w-4 h-4 text-teal-400" />
          <span>Dynamic Fields & Mathematical Formulas</span>
        </h3>
        <p class="text-xs text-zinc-500 mt-0.5">
          Build fields with user-defined enum categories, blueprint references, and multi-variable mathematical formulas.
        </p>
      </div>

      <Button variant="secondary" size="sm" onclick={addField}>
        <Plus class="w-3.5 h-3.5" />
        <span>Add Field</span>
      </Button>
    </div>

    <!-- Fields List -->
    <div class="space-y-4">
      {#if fields.length === 0}
        <div class="text-center py-8 border border-dashed border-zinc-800 rounded-lg">
          <p class="text-xs text-zinc-500">No fields defined yet. Click below to add your first field.</p>
          <Button variant="outline" size="sm" class="mt-3" onclick={addField}>
            <Plus class="w-3.5 h-3.5" />
            <span>Add Field</span>
          </Button>
        </div>
      {/if}

      {#each fields as field, index (field.id)}
        <div class="p-4 rounded-lg border border-zinc-800 bg-zinc-950/60 space-y-4 relative group">
          <!-- Field Header & Primary Definition -->
          <div class="flex items-start justify-between gap-3">
            <div class="grid grid-cols-1 sm:grid-cols-12 gap-3 flex-1">
              <!-- Field Machine Name / Key -->
              <div class="sm:col-span-4">
                <span class="block text-[11px] font-medium text-zinc-400 mb-1">Field Key (Machine Name)</span>
                <Input
                  bind:value={field.name}
                  placeholder="e.g. gender, attack, total_power"
                  class="font-mono text-xs w-full"
                />
              </div>

              <!-- Field Display Label -->
              <div class="sm:col-span-4">
                <span class="block text-[11px] font-medium text-zinc-400 mb-1">Display Label</span>
                <Input
                  bind:value={field.label}
                  placeholder="e.g. Gender, Base Attack, Combat Power"
                  class="text-xs w-full"
                />
              </div>

              <!-- Field Type Selector -->
              <div class="sm:col-span-4">
                <span class="block text-[11px] font-medium text-zinc-400 mb-1">Field Type</span>
                <Select
                  bind:value={field.fieldType}
                  options={fieldTypeOptions}
                />
              </div>
            </div>

            <!-- Delete Field Button -->
            <button
              type="button"
              onclick={() => removeField(index)}
              title="Delete Field"
              class="text-zinc-600 hover:text-red-400 p-1.5 rounded transition mt-5"
            >
              <Trash2 class="w-4 h-4" />
            </button>
          </div>

          <!-- Type-Specific Specialized Configurator -->

          <!-- 1. ENUM / DUAL-VALUED CATEGORY BUILDER -->
          {#if field.fieldType === 'ENUM'}
            <div class="p-3.5 bg-zinc-900 rounded-lg border border-zinc-800 space-y-3">
              <div class="flex items-center justify-between">
                <div class="flex items-center gap-1.5 text-xs text-teal-400 font-medium">
                  <ListFilter class="w-3.5 h-3.5" />
                  <span>Dual-Valued Enum Categories (Name + Numeric Power/Value for Formulas)</span>
                </div>
                <span class="text-[10px] text-zinc-500 font-mono">e.g. &#123; qi_refining : 100 &#125;</span>
              </div>

              <!-- Options Tags -->
              <div class="space-y-2">
                {#if field.options.length === 0}
                  <p class="text-xs text-zinc-500 italic">No options defined yet. Add an option name and numeric power below.</p>
                {/if}

                <div class="flex flex-wrap gap-2">
                  {#each field.options as opt, optIdx}
                    <div class="inline-flex items-center gap-2 px-3 py-1.5 rounded-md bg-zinc-800/90 border border-zinc-700 text-xs text-zinc-200">
                      <span class="font-medium text-zinc-100">{opt.label}</span>
                      {#if opt.power !== undefined || opt.numericValue !== undefined}
                        <span class="text-[11px] font-mono text-amber-400 bg-amber-950/60 px-1.5 py-0.5 rounded border border-amber-900/60">
                          Power: {opt.power ?? opt.numericValue}
                        </span>
                      {/if}
                      <button
                        type="button"
                        onclick={() => removeOptionFromField(index, optIdx)}
                        class="text-zinc-400 hover:text-red-400 transition ml-1"
                        title="Remove Option"
                      >
                        &times;
                      </button>
                    </div>
                  {/each}
                </div>
              </div>

              <!-- Add Dual-Valued Option Inputs -->
              <div class="grid grid-cols-1 sm:grid-cols-12 gap-2 pt-1">
                <div class="sm:col-span-6">
                  <Input
                    bind:value={field.newOptionLabel}
                    placeholder="Option Name (e.g. Qi Refining, Foundation)"
                    class="text-xs"
                    onkeydown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        addOptionToField(index);
                      }
                    }}
                  />
                </div>
                <div class="sm:col-span-4">
                  <Input
                    type="number"
                    bind:value={field.newOptionPower}
                    placeholder="Power / Numeric Value (e.g. 100)"
                    class="text-xs font-mono"
                    onkeydown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        addOptionToField(index);
                      }
                    }}
                  />
                </div>
                <div class="sm:col-span-2">
                  <Button variant="secondary" size="sm" class="w-full h-9" onclick={() => addOptionToField(index)}>
                    <Plus class="w-3 h-3" />
                    <span>Add</span>
                  </Button>
                </div>
              </div>
            </div>
          {/if}

          <!-- 2. BLUEPRINT REFERENCE BUILDER -->
          {#if field.fieldType === 'BLUEPRINT_REF'}
            <div class="p-3 bg-zinc-900/90 rounded border border-zinc-800/80 space-y-2.5">
              <div class="flex items-center gap-1.5 text-xs text-cyan-400 font-medium">
                <Link2 class="w-3.5 h-3.5" />
                <span>Target Referenced Blueprint (1st-Class or 2nd-Class)</span>
              </div>
              <p class="text-[11px] text-zinc-400">
                Allows this field to embed or reference properties from another blueprint (e.g. "Romantic Affection Scale" or "Cultivation Rank").
              </p>
              <div class="max-w-md">
                <Select
                  bind:value={field.targetBlueprintId}
                  options={availableTargetBlueprints}
                />
              </div>
            </div>
          {/if}

          <!-- 3. MATHEMATICAL & LOGICAL FORMULA BUILDER -->
          {#if field.fieldType === 'FORMULA'}
            <div class="p-3.5 bg-zinc-900 rounded border border-amber-900/40 space-y-3">
              <div class="flex items-center justify-between">
                <div class="flex items-center gap-1.5 text-xs text-amber-400 font-semibold">
                  <Calculator class="w-4 h-4" />
                  <span>Logical & Mathematical Formula Expression</span>
                </div>
                {#if field.formulaExpression}
                  {@const validation = getFormulaValidation(field.formulaExpression)}
                  {#if validation.valid}
                    <div class="inline-flex items-center gap-1 text-[11px] text-emerald-400">
                      <Check class="w-3.5 h-3.5" />
                      <span>Valid Syntax</span>
                    </div>
                  {:else}
                    <div class="inline-flex items-center gap-1 text-[11px] text-red-400">
                      <AlertCircle class="w-3.5 h-3.5" />
                      <span>{validation.error}</span>
                    </div>
                  {/if}
                {/if}
              </div>

              <!-- Formula Expression Text Input -->
              <div>
                <Input
                  bind:value={field.formulaExpression}
                  placeholder="(cultivation.major_realm * cultivation.minor_realm) * special_Physique + attack * attack_technique_Mastery - defence * defence_technique_mastery"
                  class="font-mono text-xs w-full bg-black/60 border-amber-900/60 focus:ring-amber-500"
                />
              </div>

              <!-- Variable & Operator Quick Insertion Bar -->
              <div class="space-y-2 pt-1">
                <!-- Available Sibling Fields to Insert -->
                <div class="flex flex-wrap items-center gap-1.5">
                  <span class="text-[11px] text-zinc-500 mr-1">Insert Field:</span>
                  {#each fields.filter((f) => f.name && f.id !== field.id) as sibling}
                    <button
                      type="button"
                      onclick={() => insertTokenIntoFormula(index, sibling.name)}
                      class="text-[10px] font-mono px-2 py-0.5 rounded bg-zinc-800 text-amber-300 hover:bg-zinc-700 hover:text-amber-200 border border-zinc-700 transition"
                    >
                      {sibling.name}
                    </button>
                  {/each}

                  <!-- Common Dot-Notation Examples -->
                  <button
                    type="button"
                    onclick={() => insertTokenIntoFormula(index, 'cultivation.major_realm')}
                    class="text-[10px] font-mono px-2 py-0.5 rounded bg-zinc-800 text-teal-300 hover:bg-zinc-700 border border-zinc-700 transition"
                  >
                    cultivation.major_realm
                  </button>
                  <button
                    type="button"
                    onclick={() => insertTokenIntoFormula(index, 'cultivation.minor_realm')}
                    class="text-[10px] font-mono px-2 py-0.5 rounded bg-zinc-800 text-teal-300 hover:bg-zinc-700 border border-zinc-700 transition"
                  >
                    cultivation.minor_realm
                  </button>
                </div>

                <!-- Math Operators Bar -->
                <div class="flex flex-wrap items-center gap-1">
                  <span class="text-[11px] text-zinc-500 mr-1">Operators:</span>
                  {#each ['+', '-', '*', '/', '^', '%', '(', ')', 'IF(', 'CLAMP(', 'MIN(', 'MAX(', 'SQRT('] as op}
                    <button
                      type="button"
                      onclick={() => insertTokenIntoFormula(index, op)}
                      class="text-[10px] font-mono px-2 py-0.5 rounded bg-zinc-950 text-zinc-300 hover:bg-zinc-800 border border-zinc-800 transition"
                    >
                      {op}
                    </button>
                  {/each}
                </div>
              </div>
            </div>
          {/if}

          <!-- 4. NUMBER BOUNDS & UNIT -->
          {#if field.fieldType === 'NUMBER'}
            <div class="grid grid-cols-2 sm:grid-cols-4 gap-2.5 p-3 bg-zinc-900/80 rounded border border-zinc-800">
              <div>
                <span class="block text-[10px] text-zinc-400 mb-1">Min Value</span>
                <Input type="number" bind:value={field.min} class="text-xs" />
              </div>
              <div>
                <span class="block text-[10px] text-zinc-400 mb-1">Max Value</span>
                <Input type="number" bind:value={field.max} class="text-xs" />
              </div>
              <div>
                <span class="block text-[10px] text-zinc-400 mb-1">Step</span>
                <Input type="number" bind:value={field.step} class="text-xs" />
              </div>
              <div>
                <span class="block text-[10px] text-zinc-400 mb-1">Metric Unit (e.g. Pts, Atk)</span>
                <Input bind:value={field.unit} placeholder="e.g. Pts" class="text-xs" />
              </div>
            </div>
          {/if}
        </div>
      {/each}
    </div>
  </div>

  <!-- Actions -->
  <div class="flex items-center justify-end gap-3 pt-4 border-t border-zinc-800">
    <a href="/world/schemas">
      <Button variant="outline" size="sm">Cancel</Button>
    </a>
    <Button variant="default" size="sm" onclick={handleCreateBlueprint}>
      <Check class="w-3.5 h-3.5" />
      <span>Save Blueprint Definition</span>
    </Button>
  </div>
</div>

// apps/mobile/app/world/blueprints/create.tsx
import React, { useState } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  SafeAreaView,
  Switch,
} from "react-native";
import { router } from "expo-router";
import {
  ArrowLeft,
  Boxes,
  Plus,
  Trash2,
  Sparkles,
  AlertCircle,
  Check,
  Calculator,
  Shield,
  Layers,
} from "lucide-react-native";
import { mobileStore } from "../../../src/lib/mobileStore.ts";
import {
  BlueprintClass,
  BlueprintFieldType,
  DynamicFieldDef,
} from "../../../src/lib/types.ts";
import { validateFormulaSyntax } from "../../../src/lib/formulaEngine.ts";

const SUGGESTED_CATEGORIES = [
  "Characters",
  "Relics & Armaments",
  "Cosmology & Geography",
  "Sects & Factions",
  "Systems & Affection",
  "Power Systems",
];

const FIELD_TYPES: { value: BlueprintFieldType; label: string }[] = [
  { value: "STRING", label: "Text (String)" },
  { value: "NUMBER", label: "Number (Numeric Bound)" },
  { value: "BOOLEAN", label: "Toggle (Boolean)" },
  { value: "ENUM", label: "Enum (Discrete String Options)" },
  { value: "VALUE_TYPE", label: "Value Type (Enum with Power Weights)" },
  { value: "ARRAY", label: "Array / Tag List" },
  { value: "BLUEPRINT_REF", label: "Blueprint Reference" },
  { value: "ARRAY_REF", label: "Array of Blueprint References" },
  { value: "FORMULA", label: "Formula (AST Math Evaluation)" },
];

export default function CreateBlueprintScreen() {
  const [name, setName] = useState("");
  const [blueprintClass, setBlueprintClass] =
    useState<BlueprintClass>("FIRST_CLASS");
  const [category, setCategory] = useState("Characters");
  const [customCategory, setCustomCategory] = useState("");
  const [isCustomCategory, setIsCustomCategory] = useState(false);
  const [description, setDescription] = useState("");
  const [fields, setFields] = useState<DynamicFieldDef[]>([
    {
      id: `f-${Date.now()}-1`,
      name: "name",
      key: "name",
      label: "Entity Name",
      fieldType: "STRING",
      required: true,
      description: "Canonical identity name",
    },
  ]);
  const [error, setError] = useState<string | null>(null);

  const existingBlueprints = mobileStore.getBlueprints();

  const addField = () => {
    const newFieldId = `f-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    setFields((prev) => [
      ...prev,
      {
        id: newFieldId,
        name: `field_${prev.length + 1}`,
        key: `field_${prev.length + 1}`,
        label: `Field ${prev.length + 1}`,
        fieldType: "STRING",
        required: false,
      },
    ]);
  };

  const updateField = (index: number, updates: Partial<DynamicFieldDef>) => {
    setFields((prev) =>
      prev.map((f, i) => {
        if (i === index) {
          const updated = { ...f, ...updates };
          if (updates.name && !updates.key) {
            updated.key = updates.name
              .toLowerCase()
              .replace(/[^a-z0-9_]/g, "_");
          }
          return updated;
        }
        return f;
      }),
    );
  };

  const removeField = (index: number) => {
    setFields((prev) => prev.filter((_, i) => i !== index));
  };

  const handleSave = () => {
    const finalName = name.trim();
    if (!finalName) {
      setError("Blueprint name is required.");
      return;
    }

    const finalCategory =
      (isCustomCategory ? customCategory : category).trim() || "General";

    // Validate formula fields
    for (const f of fields) {
      if (f.fieldType === "FORMULA" && f.formulaExpression) {
        const valRes = validateFormulaSyntax(f.formulaExpression);
        if (!valRes.valid) {
          setError(
            `Invalid formula in field "${f.label || f.name}": ${valRes.error}`,
          );
          return;
        }
      }
    }

    mobileStore.createBlueprint({
      name: finalName,
      blueprintClass,
      category: finalCategory,
      description: description.trim(),
      fields,
    });

    router.back();
  };

  return (
    <SafeAreaView className="flex-1 bg-zinc-950">
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        className="flex-1"
      >
        {/* Header */}
        <View className="flex-row items-center justify-between border-b border-zinc-800 bg-zinc-900/90 px-4 py-3.5">
          <TouchableOpacity
            onPress={() => router.back()}
            activeOpacity={0.7}
            className="h-10 w-10 items-center justify-center rounded-lg border border-zinc-800 bg-zinc-950"
          >
            <ArrowLeft size={20} color="#a1a1aa" />
          </TouchableOpacity>
          <View className="flex-1 items-center px-3">
            <Text className="text-base font-bold text-zinc-100">
              Create Blueprint
            </Text>
            <Text className="text-xs text-zinc-400">
              World Architecture & Schema Def
            </Text>
          </View>
          <TouchableOpacity
            onPress={handleSave}
            activeOpacity={0.7}
            className="flex-row items-center gap-1.5 rounded-lg bg-amber-500 px-3.5 py-2"
          >
            <Sparkles size={16} color="#09090b" />
            <Text className="text-xs font-bold text-zinc-950">Save</Text>
          </TouchableOpacity>
        </View>

        <ScrollView
          className="flex-1 px-4 py-5"
          contentContainerStyle={{ paddingBottom: 60 }}
          keyboardShouldPersistTaps="handled"
        >
          {error ? (
            <View className="mb-5 flex-row items-center gap-2.5 rounded-xl border border-red-500/30 bg-red-950/30 p-3.5">
              <AlertCircle size={18} color="#ef4444" />
              <Text className="flex-1 text-xs text-red-300">{error}</Text>
            </View>
          ) : null}

          {/* Blueprint Name */}
          <View className="mb-5">
            <View className="mb-2 flex-row items-center gap-2">
              <Boxes size={16} color="#f59e0b" />
              <Text className="text-xs font-semibold uppercase tracking-wider text-zinc-300">
                Blueprint Name <Text className="text-amber-500">*</Text>
              </Text>
            </View>
            <TextInput
              value={name}
              onChangeText={(t) => {
                setName(t);
                if (error) setError(null);
              }}
              placeholder="e.g. Cultivator Archetype, Sacred Armament, Spirit Beast"
              placeholderTextColor="#71717a"
              className="rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-3 text-sm text-zinc-100"
            />
          </View>

          {/* Blueprint Class */}
          <View className="mb-5">
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-300">
              Blueprint Class Architecture
            </Text>
            <View className="flex-row gap-3">
              <TouchableOpacity
                onPress={() => setBlueprintClass("FIRST_CLASS")}
                activeOpacity={0.7}
                className={`flex-1 rounded-xl border p-3.5 ${
                  blueprintClass === "FIRST_CLASS"
                    ? "border-amber-500 bg-amber-500/10"
                    : "border-zinc-800 bg-zinc-900"
                }`}
              >
                <View className="flex-row items-center justify-between">
                  <Text
                    className={`text-xs font-bold ${
                      blueprintClass === "FIRST_CLASS"
                        ? "text-amber-400"
                        : "text-zinc-300"
                    }`}
                  >
                    1st-Class Independent
                  </Text>
                  {blueprintClass === "FIRST_CLASS" && (
                    <Check size={14} color="#f59e0b" />
                  )}
                </View>
                <Text className="mt-1 text-[11px] leading-4 text-zinc-400">
                  Primary world entity with direct timeline mutation tracking
                  and canonical state.
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={() => setBlueprintClass("SECOND_CLASS")}
                activeOpacity={0.7}
                className={`flex-1 rounded-xl border p-3.5 ${
                  blueprintClass === "SECOND_CLASS"
                    ? "border-blue-500 bg-blue-500/10"
                    : "border-zinc-800 bg-zinc-900"
                }`}
              >
                <View className="flex-row items-center justify-between">
                  <Text
                    className={`text-xs font-bold ${
                      blueprintClass === "SECOND_CLASS"
                        ? "text-blue-400"
                        : "text-zinc-300"
                    }`}
                  >
                    2nd-Class Embedded
                  </Text>
                  {blueprintClass === "SECOND_CLASS" && (
                    <Check size={14} color="#3b82f6" />
                  )}
                </View>
                <Text className="mt-1 text-[11px] leading-4 text-zinc-400">
                  Nested value object / component embedded inside parent entity
                  properties.
                </Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Category */}
          <View className="mb-5">
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-300">
              Domain Category
            </Text>
            <View className="flex-row flex-wrap gap-2">
              {SUGGESTED_CATEGORIES.map((cat) => {
                const isSelected = !isCustomCategory && category === cat;
                return (
                  <TouchableOpacity
                    key={cat}
                    onPress={() => {
                      setIsCustomCategory(false);
                      setCategory(cat);
                    }}
                    activeOpacity={0.7}
                    className={`rounded-lg border px-3 py-2 ${
                      isSelected
                        ? "border-amber-500 bg-amber-500/20"
                        : "border-zinc-800 bg-zinc-900"
                    }`}
                  >
                    <Text
                      className={`text-xs font-medium ${
                        isSelected ? "text-amber-400" : "text-zinc-400"
                      }`}
                    >
                      {cat}
                    </Text>
                  </TouchableOpacity>
                );
              })}
              <TouchableOpacity
                onPress={() => setIsCustomCategory(true)}
                activeOpacity={0.7}
                className={`rounded-lg border px-3 py-2 ${
                  isCustomCategory
                    ? "border-amber-500 bg-amber-500/20"
                    : "border-zinc-800 bg-zinc-900"
                }`}
              >
                <Text
                  className={`text-xs font-medium ${
                    isCustomCategory ? "text-amber-400" : "text-zinc-400"
                  }`}
                >
                  Custom Category...
                </Text>
              </TouchableOpacity>
            </View>
            {isCustomCategory && (
              <TextInput
                value={customCategory}
                onChangeText={setCustomCategory}
                placeholder="Enter custom category..."
                placeholderTextColor="#71717a"
                className="mt-3 rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-3 text-sm text-zinc-100"
              />
            )}
          </View>

          {/* Description */}
          <View className="mb-6">
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-300">
              Blueprint Lore Description & Contract
            </Text>
            <TextInput
              value={description}
              onChangeText={setDescription}
              placeholder="Describe what entities derived from this blueprint represent in your universe..."
              placeholderTextColor="#71717a"
              multiline
              numberOfLines={3}
              textAlignVertical="top"
              className="min-h-[80px] rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-3 text-sm text-zinc-100"
            />
          </View>

          {/* Dynamic Schema Fields Section */}
          <View className="mb-6">
            <View className="mb-3 flex-row items-center justify-between">
              <View className="flex-row items-center gap-2">
                <Layers size={16} color="#f59e0b" />
                <Text className="text-xs font-semibold uppercase tracking-wider text-zinc-200">
                  Dynamic Schema Fields ({fields.length})
                </Text>
              </View>
              <TouchableOpacity
                onPress={addField}
                activeOpacity={0.7}
                className="flex-row items-center gap-1 rounded-lg border border-amber-500/40 bg-amber-500/10 px-3 py-1.5"
              >
                <Plus size={14} color="#f59e0b" />
                <Text className="text-xs font-bold text-amber-400">
                  Add Field
                </Text>
              </TouchableOpacity>
            </View>

            <View className="gap-3">
              {fields.map((field, idx) => (
                <View
                  key={field.id}
                  className="rounded-xl border border-zinc-800 bg-zinc-900/90 p-4"
                >
                  <View className="mb-3 flex-row items-center justify-between">
                    <View className="flex-row items-center gap-2">
                      <View className="h-6 w-6 items-center justify-center rounded-full bg-zinc-800">
                        <Text className="text-xs font-bold text-zinc-300">
                          {idx + 1}
                        </Text>
                      </View>
                      <Text className="text-xs font-bold text-zinc-200">
                        {field.label || field.name || `Field ${idx + 1}`}
                      </Text>
                    </View>
                    {fields.length > 1 && (
                      <TouchableOpacity
                        onPress={() => removeField(idx)}
                        activeOpacity={0.7}
                        className="rounded-lg p-1.5 hover:bg-zinc-800"
                      >
                        <Trash2 size={16} color="#ef4444" />
                      </TouchableOpacity>
                    )}
                  </View>

                  {/* Field Label & Machine Key */}
                  <View className="mb-3 flex-row gap-2">
                    <View className="flex-1">
                      <Text className="mb-1 text-[11px] font-semibold text-zinc-400">
                        Display Label
                      </Text>
                      <TextInput
                        value={field.label || field.name}
                        onChangeText={(t) =>
                          updateField(idx, { label: t, name: t })
                        }
                        placeholder="e.g. Base Qi, Cultivation Realm"
                        placeholderTextColor="#71717a"
                        className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 text-xs text-zinc-100"
                      />
                    </View>
                    <View className="flex-1">
                      <Text className="mb-1 text-[11px] font-semibold text-zinc-400">
                        Machine Key
                      </Text>
                      <TextInput
                        value={field.key || field.name}
                        onChangeText={(t) => updateField(idx, { key: t })}
                        placeholder="e.g. base_qi, realm"
                        placeholderTextColor="#71717a"
                        className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 font-mono text-xs text-amber-300"
                      />
                    </View>
                  </View>

                  {/* Field Type Picker */}
                  <View className="mb-3">
                    <Text className="mb-1.5 text-[11px] font-semibold text-zinc-400">
                      Field Type
                    </Text>
                    <ScrollView
                      horizontal
                      showsHorizontalScrollIndicator={false}
                      className="flex-row gap-1.5"
                    >
                      {FIELD_TYPES.map((ft) => {
                        const isSelected = field.fieldType === ft.value;
                        return (
                          <TouchableOpacity
                            key={ft.value}
                            onPress={() =>
                              updateField(idx, { fieldType: ft.value })
                            }
                            activeOpacity={0.7}
                            className={`mr-1.5 rounded-lg border px-2.5 py-1.5 ${
                              isSelected
                                ? "border-amber-500 bg-amber-500/20"
                                : "border-zinc-800 bg-zinc-950"
                            }`}
                          >
                            <Text
                              className={`text-[11px] font-medium ${
                                isSelected ? "text-amber-400" : "text-zinc-400"
                              }`}
                            >
                              {ft.label}
                            </Text>
                          </TouchableOpacity>
                        );
                      })}
                    </ScrollView>
                  </View>

                  {/* FORMULA Field Editor */}
                  {field.fieldType === "FORMULA" && (
                    <View className="mb-3 rounded-lg border border-violet-500/30 bg-violet-950/20 p-3">
                      <View className="mb-1.5 flex-row items-center gap-1.5">
                        <Calculator size={14} color="#a78bfa" />
                        <Text className="text-[11px] font-bold text-violet-300">
                          Formula Expression (AST Evaluated)
                        </Text>
                      </View>
                      <TextInput
                        value={field.formulaExpression || ""}
                        onChangeText={(t) =>
                          updateField(idx, { formulaExpression: t })
                        }
                        placeholder="e.g. (base_qi + gear_bonus) * multiplier + 50"
                        placeholderTextColor="#71717a"
                        className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 font-mono text-xs text-violet-200"
                      />
                      <Text className="mt-1.5 text-[10px] text-zinc-400">
                        Supports +, -, *, /, %, POW(x,y), SQRT(x),
                        CLAMP(v,min,max), MIN, MAX, IF(cond, then, else).
                      </Text>
                    </View>
                  )}

                  {/* ENUM / VALUE_TYPE Options Editor */}
                  {(field.fieldType === "ENUM" ||
                    field.fieldType === "VALUE_TYPE") && (
                    <View className="mb-3 rounded-lg border border-zinc-800 bg-zinc-950 p-3">
                      <Text className="mb-1.5 text-[11px] font-semibold text-zinc-300">
                        Discrete Options (Comma-separated or with :power)
                      </Text>
                      <TextInput
                        value={
                          Array.isArray(field.options)
                            ? field.options
                                .map((o) =>
                                  typeof o === "string"
                                    ? o
                                    : `${o.label}:${o.power ?? o.numericValue ?? 0}`,
                                )
                                .join(", ")
                            : ""
                        }
                        onChangeText={(t) => {
                          const rawOpts = t
                            .split(",")
                            .map((s) => s.trim())
                            .filter(Boolean);
                          const parsed = rawOpts.map((optStr) => {
                            if (optStr.includes(":")) {
                              const [lbl, pwr] = optStr.split(":");
                              const numPwr = Number(pwr.trim()) || 0;
                              return {
                                label: lbl.trim(),
                                value: lbl.trim(),
                                power: numPwr,
                                numericValue: numPwr,
                              };
                            }
                            return optStr;
                          });
                          updateField(idx, { options: parsed });
                        }}
                        placeholder="e.g. Qi Refining:100, Foundation:500, Core Formation:2500"
                        placeholderTextColor="#71717a"
                        className="rounded-lg border border-zinc-800 bg-zinc-900 px-3 py-2 text-xs text-zinc-100"
                      />
                    </View>
                  )}

                  {/* NUMBER Bounds */}
                  {field.fieldType === "NUMBER" && (
                    <View className="mb-3 flex-row gap-2">
                      <View className="flex-1">
                        <Text className="mb-1 text-[10px] text-zinc-400">
                          Min Bound
                        </Text>
                        <TextInput
                          value={
                            field.min !== undefined ? String(field.min) : ""
                          }
                          onChangeText={(t) =>
                            updateField(idx, {
                              min: t === "" ? undefined : Number(t),
                            })
                          }
                          keyboardType="numeric"
                          placeholder="0"
                          placeholderTextColor="#71717a"
                          className="rounded border border-zinc-800 bg-zinc-950 px-2 py-1.5 text-xs text-zinc-100"
                        />
                      </View>
                      <View className="flex-1">
                        <Text className="mb-1 text-[10px] text-zinc-400">
                          Max Bound
                        </Text>
                        <TextInput
                          value={
                            field.max !== undefined ? String(field.max) : ""
                          }
                          onChangeText={(t) =>
                            updateField(idx, {
                              max: t === "" ? undefined : Number(t),
                            })
                          }
                          keyboardType="numeric"
                          placeholder="99999"
                          placeholderTextColor="#71717a"
                          className="rounded border border-zinc-800 bg-zinc-950 px-2 py-1.5 text-xs text-zinc-100"
                        />
                      </View>
                      <View className="flex-1">
                        <Text className="mb-1 text-[10px] text-zinc-400">
                          Default Value
                        </Text>
                        <TextInput
                          value={
                            field.defaultValue !== undefined
                              ? String(field.defaultValue)
                              : ""
                          }
                          onChangeText={(t) =>
                            updateField(idx, {
                              defaultValue: t === "" ? undefined : Number(t),
                            })
                          }
                          keyboardType="numeric"
                          placeholder="100"
                          placeholderTextColor="#71717a"
                          className="rounded border border-zinc-800 bg-zinc-950 px-2 py-1.5 text-xs text-zinc-100"
                        />
                      </View>
                    </View>
                  )}

                  {/* Required Switch */}
                  <View className="flex-row items-center justify-between pt-1">
                    <Text className="text-xs text-zinc-400">
                      Required Field (Validation Guard)
                    </Text>
                    <Switch
                      value={!!field.required}
                      onValueChange={(v) => updateField(idx, { required: v })}
                      trackColor={{ false: "#27272a", true: "#f59e0b" }}
                      thumbColor="#ffffff"
                    />
                  </View>
                </View>
              ))}
            </View>
          </View>

          {/* Action Buttons */}
          <View className="gap-3">
            <TouchableOpacity
              onPress={handleSave}
              activeOpacity={0.7}
              className="flex-row items-center justify-center gap-2 rounded-xl bg-amber-500 py-3.5"
            >
              <Check size={18} color="#09090b" />
              <Text className="text-sm font-bold text-zinc-950">
                Save Blueprint Definition
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              onPress={() => router.back()}
              activeOpacity={0.7}
              className="items-center justify-center rounded-xl border border-zinc-800 bg-zinc-900 py-3.5"
            >
              <Text className="text-sm font-medium text-zinc-400">Cancel</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
