// apps/mobile/app/world/blueprints/[id].tsx
import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  SafeAreaView,
  Switch,
  Alert,
} from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import {
  ArrowLeft,
  Boxes,
  Plus,
  Trash2,
  Sparkles,
  AlertCircle,
  Check,
  Calculator,
  Layers,
} from "lucide-react-native";
import { mobileStore } from "../../../src/lib/mobileStore.ts";
import {
  BlueprintClass,
  BlueprintFieldType,
  DynamicFieldDef,
} from "../../../src/lib/types.ts";
import { validateFormulaSyntax } from "../../../src/lib/formulaEngine.ts";

const SUGGESTED_CATEGORIES = [
  "Characters",
  "Relics & Armaments",
  "Cosmology & Geography",
  "Sects & Factions",
  "Systems & Affection",
  "Power Systems",
];

const FIELD_TYPES: { value: BlueprintFieldType; label: string }[] = [
  { value: "STRING", label: "Text (String)" },
  { value: "NUMBER", label: "Number (Numeric Bound)" },
  { value: "BOOLEAN", label: "Toggle (Boolean)" },
  { value: "ENUM", label: "Enum (Discrete String Options)" },
  { value: "VALUE_TYPE", label: "Value Type (Enum with Power Weights)" },
  { value: "ARRAY", label: "Array / Tag List" },
  { value: "BLUEPRINT_REF", label: "Blueprint Reference" },
  { value: "ARRAY_REF", label: "Array of Blueprint References" },
  { value: "FORMULA", label: "Formula (AST Math Evaluation)" },
];

export default function EditBlueprintScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [blueprint, setBlueprint] = useState(() =>
    id ? mobileStore.getBlueprint(id) : undefined,
  );

  const [name, setName] = useState(blueprint?.name || "");
  const [blueprintClass, setBlueprintClass] = useState<BlueprintClass>(
    blueprint?.blueprintClass || "FIRST_CLASS",
  );
  const [category, setCategory] = useState(blueprint?.category || "Characters");
  const [customCategory, setCustomCategory] = useState("");
  const [isCustomCategory, setIsCustomCategory] = useState(false);
  const [description, setDescription] = useState(blueprint?.description || "");
  const [fields, setFields] = useState<DynamicFieldDef[]>(
    blueprint?.fields || [],
  );
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (id) {
      const bp = mobileStore.getBlueprint(id);
      if (bp) {
        setBlueprint(bp);
        setName(bp.name);
        setBlueprintClass(bp.blueprintClass);
        setCategory(bp.category);
        setDescription(bp.description || "");
        setFields(bp.fields);
      }
    }
  }, [id]);

  if (!blueprint) {
    return (
      <SafeAreaView className="flex-1 bg-zinc-950 px-4 py-8 items-center justify-center">
        <AlertCircle size={32} color="#ef4444" />
        <Text className="mt-3 text-base font-bold text-zinc-100">
          Blueprint Not Found
        </Text>
        <TouchableOpacity
          onPress={() => router.back()}
          className="mt-4 rounded-xl bg-zinc-900 border border-zinc-800 px-4 py-2.5"
        >
          <Text className="text-xs text-zinc-300">Go Back</Text>
        </TouchableOpacity>
      </SafeAreaView>
    );
  }

  const addField = () => {
    const newFieldId = `f-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    setFields((prev) => [
      ...prev,
      {
        id: newFieldId,
        name: `field_${prev.length + 1}`,
        key: `field_${prev.length + 1}`,
        label: `Field ${prev.length + 1}`,
        fieldType: "STRING",
        required: false,
      },
    ]);
  };

  const updateField = (index: number, updates: Partial<DynamicFieldDef>) => {
    setFields((prev) =>
      prev.map((f, i) => {
        if (i === index) {
          const updated = { ...f, ...updates };
          if (updates.name && !updates.key) {
            updated.key = updates.name
              .toLowerCase()
              .replace(/[^a-z0-9_]/g, "_");
          }
          return updated;
        }
        return f;
      }),
    );
  };

  const removeField = (index: number) => {
    setFields((prev) => prev.filter((_, i) => i !== index));
  };

  const handleSave = () => {
    const finalName = name.trim();
    if (!finalName) {
      setError("Blueprint name is required.");
      return;
    }

    const finalCategory =
      (isCustomCategory ? customCategory : category).trim() || "General";

    // Validate formula fields
    for (const f of fields) {
      if (f.fieldType === "FORMULA" && f.formulaExpression) {
        const valRes = validateFormulaSyntax(f.formulaExpression);
        if (!valRes.valid) {
          setError(
            `Invalid formula in field "${f.label || f.name}": ${valRes.error}`,
          );
          return;
        }
      }
    }

    if (id) {
      mobileStore.updateBlueprint(id, {
        name: finalName,
        blueprintClass,
        category: finalCategory,
        description: description.trim(),
        fields,
      });
    }

    router.back();
  };

  const handleDelete = () => {
    if (!id) return;
    Alert.alert(
      "Delete Blueprint Definition",
      `Are you sure you want to delete "${blueprint.name}"? This will also remove all associated entities from the active universe.`,
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Delete",
          style: "destructive",
          onPress: () => {
            mobileStore.deleteBlueprint(id);
            router.back();
          },
        },
      ],
    );
  };

  return (
    <SafeAreaView className="flex-1 bg-zinc-950">
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        className="flex-1"
      >
        {/* Header */}
        <View className="flex-row items-center justify-between border-b border-zinc-800 bg-zinc-900/90 px-4 py-3.5">
          <TouchableOpacity
            onPress={() => router.back()}
            activeOpacity={0.7}
            className="h-10 w-10 items-center justify-center rounded-lg border border-zinc-800 bg-zinc-950"
          >
            <ArrowLeft size={20} color="#a1a1aa" />
          </TouchableOpacity>
          <View className="flex-1 items-center px-3">
            <Text className="text-base font-bold text-zinc-100">
              Edit Blueprint
            </Text>
            <Text className="text-xs text-zinc-400">{blueprint.name}</Text>
          </View>
          <TouchableOpacity
            onPress={handleSave}
            activeOpacity={0.7}
            className="flex-row items-center gap-1.5 rounded-lg bg-amber-500 px-3.5 py-2"
          >
            <Sparkles size={16} color="#09090b" />
            <Text className="text-xs font-bold text-zinc-950">Save</Text>
          </TouchableOpacity>
        </View>

        <ScrollView
          className="flex-1 px-4 py-5"
          contentContainerStyle={{ paddingBottom: 60 }}
          keyboardShouldPersistTaps="handled"
        >
          {error ? (
            <View className="mb-5 flex-row items-center gap-2.5 rounded-xl border border-red-500/30 bg-red-950/30 p-3.5">
              <AlertCircle size={18} color="#ef4444" />
              <Text className="flex-1 text-xs text-red-300">{error}</Text>
            </View>
          ) : null}

          {/* Blueprint Name */}
          <View className="mb-5">
            <View className="mb-2 flex-row items-center gap-2">
              <Boxes size={16} color="#f59e0b" />
              <Text className="text-xs font-semibold uppercase tracking-wider text-zinc-300">
                Blueprint Name <Text className="text-amber-500">*</Text>
              </Text>
            </View>
            <TextInput
              value={name}
              onChangeText={(t) => {
                setName(t);
                if (error) setError(null);
              }}
              placeholder="e.g. Cultivator Archetype, Sacred Armament"
              placeholderTextColor="#71717a"
              className="rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-3 text-sm text-zinc-100"
            />
          </View>

          {/* Blueprint Class */}
          <View className="mb-5">
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-300">
              Blueprint Class Architecture
            </Text>
            <View className="flex-row gap-3">
              <TouchableOpacity
                onPress={() => setBlueprintClass("FIRST_CLASS")}
                activeOpacity={0.7}
                className={`flex-1 rounded-xl border p-3.5 ${
                  blueprintClass === "FIRST_CLASS"
                    ? "border-amber-500 bg-amber-500/10"
                    : "border-zinc-800 bg-zinc-900"
                }`}
              >
                <View className="flex-row items-center justify-between">
                  <Text
                    className={`text-xs font-bold ${
                      blueprintClass === "FIRST_CLASS"
                        ? "text-amber-400"
                        : "text-zinc-300"
                    }`}
                  >
                    1st-Class Independent
                  </Text>
                  {blueprintClass === "FIRST_CLASS" && (
                    <Check size={14} color="#f59e0b" />
                  )}
                </View>
                <Text className="mt-1 text-[11px] leading-4 text-zinc-400">
                  Direct timeline mutation tracking and canonical state.
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                onPress={() => setBlueprintClass("SECOND_CLASS")}
                activeOpacity={0.7}
                className={`flex-1 rounded-xl border p-3.5 ${
                  blueprintClass === "SECOND_CLASS"
                    ? "border-blue-500 bg-blue-500/10"
                    : "border-zinc-800 bg-zinc-900"
                }`}
              >
                <View className="flex-row items-center justify-between">
                  <Text
                    className={`text-xs font-bold ${
                      blueprintClass === "SECOND_CLASS"
                        ? "text-blue-400"
                        : "text-zinc-300"
                    }`}
                  >
                    2nd-Class Embedded
                  </Text>
                  {blueprintClass === "SECOND_CLASS" && (
                    <Check size={14} color="#3b82f6" />
                  )}
                </View>
                <Text className="mt-1 text-[11px] leading-4 text-zinc-400">
                  Embedded inside parent entity properties.
                </Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Category */}
          <View className="mb-5">
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-300">
              Domain Category
            </Text>
            <View className="flex-row flex-wrap gap-2">
              {SUGGESTED_CATEGORIES.map((cat) => {
                const isSelected = !isCustomCategory && category === cat;
                return (
                  <TouchableOpacity
                    key={cat}
                    onPress={() => {
                      setIsCustomCategory(false);
                      setCategory(cat);
                    }}
                    activeOpacity={0.7}
                    className={`rounded-lg border px-3 py-2 ${
                      isSelected
                        ? "border-amber-500 bg-amber-500/20"
                        : "border-zinc-800 bg-zinc-900"
                    }`}
                  >
                    <Text
                      className={`text-xs font-medium ${
                        isSelected ? "text-amber-400" : "text-zinc-400"
                      }`}
                    >
                      {cat}
                    </Text>
                  </TouchableOpacity>
                );
              })}
            </View>
          </View>

          {/* Description */}
          <View className="mb-6">
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-300">
              Lore Description & Contract
            </Text>
            <TextInput
              value={description}
              onChangeText={setDescription}
              placeholder="Describe what entities derived from this blueprint represent..."
              placeholderTextColor="#71717a"
              multiline
              numberOfLines={3}
              textAlignVertical="top"
              className="min-h-[80px] rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-3 text-sm text-zinc-100"
            />
          </View>

          {/* Dynamic Schema Fields Section */}
          <View className="mb-6">
            <View className="mb-3 flex-row items-center justify-between">
              <View className="flex-row items-center gap-2">
                <Layers size={16} color="#f59e0b" />
                <Text className="text-xs font-semibold uppercase tracking-wider text-zinc-200">
                  Dynamic Schema Fields ({fields.length})
                </Text>
              </View>
              <TouchableOpacity
                onPress={addField}
                activeOpacity={0.7}
                className="flex-row items-center gap-1 rounded-lg border border-amber-500/40 bg-amber-500/10 px-3 py-1.5"
              >
                <Plus size={14} color="#f59e0b" />
                <Text className="text-xs font-bold text-amber-400">
                  Add Field
                </Text>
              </TouchableOpacity>
            </View>

            <View className="gap-3">
              {fields.map((field, idx) => (
                <View
                  key={field.id}
                  className="rounded-xl border border-zinc-800 bg-zinc-900/90 p-4"
                >
                  <View className="mb-3 flex-row items-center justify-between">
                    <View className="flex-row items-center gap-2">
                      <View className="h-6 w-6 items-center justify-center rounded-full bg-zinc-800">
                        <Text className="text-xs font-bold text-zinc-300">
                          {idx + 1}
                        </Text>
                      </View>
                      <Text className="text-xs font-bold text-zinc-200">
                        {field.label || field.name || `Field ${idx + 1}`}
                      </Text>
                    </View>
                    {fields.length > 1 && (
                      <TouchableOpacity
                        onPress={() => removeField(idx)}
                        activeOpacity={0.7}
                        className="rounded-lg p-1.5 hover:bg-zinc-800"
                      >
                        <Trash2 size={16} color="#ef4444" />
                      </TouchableOpacity>
                    )}
                  </View>

                  {/* Field Label & Machine Key */}
                  <View className="mb-3 flex-row gap-2">
                    <View className="flex-1">
                      <Text className="mb-1 text-[11px] font-semibold text-zinc-400">
                        Display Label
                      </Text>
                      <TextInput
                        value={field.label || field.name}
                        onChangeText={(t) =>
                          updateField(idx, { label: t, name: t })
                        }
                        placeholder="e.g. Base Qi"
                        placeholderTextColor="#71717a"
                        className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 text-xs text-zinc-100"
                      />
                    </View>
                    <View className="flex-1">
                      <Text className="mb-1 text-[11px] font-semibold text-zinc-400">
                        Machine Key
                      </Text>
                      <TextInput
                        value={field.key || field.name}
                        onChangeText={(t) => updateField(idx, { key: t })}
                        placeholder="e.g. base_qi"
                        placeholderTextColor="#71717a"
                        className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 font-mono text-xs text-amber-300"
                      />
                    </View>
                  </View>

                  {/* Field Type Picker */}
                  <View className="mb-3">
                    <Text className="mb-1.5 text-[11px] font-semibold text-zinc-400">
                      Field Type
                    </Text>
                    <ScrollView
                      horizontal
                      showsHorizontalScrollIndicator={false}
                      className="flex-row gap-1.5"
                    >
                      {FIELD_TYPES.map((ft) => {
                        const isSelected = field.fieldType === ft.value;
                        return (
                          <TouchableOpacity
                            key={ft.value}
                            onPress={() =>
                              updateField(idx, { fieldType: ft.value })
                            }
                            activeOpacity={0.7}
                            className={`mr-1.5 rounded-lg border px-2.5 py-1.5 ${
                              isSelected
                                ? "border-amber-500 bg-amber-500/20"
                                : "border-zinc-800 bg-zinc-950"
                            }`}
                          >
                            <Text
                              className={`text-[11px] font-medium ${
                                isSelected ? "text-amber-400" : "text-zinc-400"
                              }`}
                            >
                              {ft.label}
                            </Text>
                          </TouchableOpacity>
                        );
                      })}
                    </ScrollView>
                  </View>

                  {/* FORMULA Field Editor */}
                  {field.fieldType === "FORMULA" && (
                    <View className="mb-3 rounded-lg border border-violet-500/30 bg-violet-950/20 p-3">
                      <View className="mb-1.5 flex-row items-center gap-1.5">
                        <Calculator size={14} color="#a78bfa" />
                        <Text className="text-[11px] font-bold text-violet-300">
                          Formula Expression (AST Evaluated)
                        </Text>
                      </View>
                      <TextInput
                        value={field.formulaExpression || ""}
                        onChangeText={(t) =>
                          updateField(idx, { formulaExpression: t })
                        }
                        placeholder="e.g. (base_qi + gear_bonus) * multiplier"
                        placeholderTextColor="#71717a"
                        className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2 font-mono text-xs text-violet-200"
                      />
                    </View>
                  )}

                  {/* ENUM / VALUE_TYPE Options Editor */}
                  {(field.fieldType === "ENUM" ||
                    field.fieldType === "VALUE_TYPE") && (
                    <View className="mb-3 rounded-lg border border-zinc-800 bg-zinc-950 p-3">
                      <Text className="mb-1.5 text-[11px] font-semibold text-zinc-300">
                        Discrete Options (Comma-separated or label:power)
                      </Text>
                      <TextInput
                        value={
                          Array.isArray(field.options)
                            ? field.options
                                .map((o) =>
                                  typeof o === "string"
                                    ? o
                                    : `${o.label}:${o.power ?? o.numericValue ?? 0}`,
                                )
                                .join(", ")
                            : ""
                        }
                        onChangeText={(t) => {
                          const rawOpts = t
                            .split(",")
                            .map((s) => s.trim())
                            .filter(Boolean);
                          const parsed = rawOpts.map((optStr) => {
                            if (optStr.includes(":")) {
                              const [lbl, pwr] = optStr.split(":");
                              const numPwr = Number(pwr.trim()) || 0;
                              return {
                                label: lbl.trim(),
                                value: lbl.trim(),
                                power: numPwr,
                                numericValue: numPwr,
                              };
                            }
                            return optStr;
                          });
                          updateField(idx, { options: parsed });
                        }}
                        placeholder="e.g. Qi Refining:100, Foundation:500"
                        placeholderTextColor="#71717a"
                        className="rounded-lg border border-zinc-800 bg-zinc-900 px-3 py-2 text-xs text-zinc-100"
                      />
                    </View>
                  )}

                  {/* Required Switch */}
                  <View className="flex-row items-center justify-between pt-1">
                    <Text className="text-xs text-zinc-400">
                      Required Field
                    </Text>
                    <Switch
                      value={!!field.required}
                      onValueChange={(v) => updateField(idx, { required: v })}
                      trackColor={{ false: "#27272a", true: "#f59e0b" }}
                      thumbColor="#ffffff"
                    />
                  </View>
                </View>
              ))}
            </View>
          </View>

          {/* Action Buttons */}
          <View className="gap-3">
            <TouchableOpacity
              onPress={handleSave}
              activeOpacity={0.7}
              className="flex-row items-center justify-center gap-2 rounded-xl bg-amber-500 py-3.5"
            >
              <Check size={18} color="#09090b" />
              <Text className="text-sm font-bold text-zinc-950">
                Save Blueprint Changes
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              onPress={handleDelete}
              activeOpacity={0.7}
              className="flex-row items-center justify-center gap-2 rounded-xl border border-red-500/40 bg-red-950/20 py-3.5"
            >
              <Trash2 size={16} color="#ef4444" />
              <Text className="text-sm font-semibold text-red-400">
                Delete Blueprint Definition
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              onPress={() => router.back()}
              activeOpacity={0.7}
              className="items-center justify-center rounded-xl border border-zinc-800 bg-zinc-900 py-3.5"
            >
              <Text className="text-sm font-medium text-zinc-400">Cancel</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

// apps/web/src/routes/world/schemas/[id]/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { goto } from '$app/navigation';
  import {
    ArrowLeft,
    Check,
    Plus,
    Trash2,
    Boxes,
    Layers,
    Calculator,
    Link2,
    ListFilter,
    Hash,
    Sparkles,
    AlertCircle,
    Play,
    Shield,
  } from 'lucide-svelte';
  import Button from '$lib/components/ui/button.svelte';
  import Input from '$lib/components/ui/input.svelte';
  import Select from '$lib/components/ui/select.svelte';
  import Label from '$lib/components/ui/label.svelte';
  import Field from '$lib/components/ui/field.svelte';
  import Textarea from '$lib/components/ui/textarea.svelte';
  import Breadcrumb from '$lib/components/ui/breadcrumb.svelte';
  import {
    worldStore,
    type BlueprintClass,
    type BlueprintFieldType,
    type DynamicFieldDef,
  } from '$lib/stores/worldStore.svelte';
  import {
    evaluateFormula,
    extractFormulaVariables,
    validateFormulaSyntax,
  } from '$lib/engine/formulaEngine';

  const blueprintId = $derived(page.params.id);
  const blueprint = $derived(worldStore.getBlueprint(blueprintId));

  let name = $state('');
  let blueprintClass = $state<BlueprintClass>('FIRST_CLASS');
  let category = $state('');
  let description = $state('');
  let saveMessage = $state<string | null>(null);

  // New field draft state
  let showNewFieldModal = $state(false);
  let newFieldName = $state('');
  let newFieldLabel = $state('');
  let newFieldType = $state<BlueprintFieldType>('STRING');
  let newFieldDesc = $state('');
  let newFieldOptions = $state<Array<{ label: string; value: string; power?: number; numericValue?: number }>>([
    { label: 'Option A', value: 'option_a', power: 100, numericValue: 100 },
    { label: 'Option B', value: 'option_b', power: 500, numericValue: 500 },
  ]);
  let newOptionLabelDraft = $state('');
  let newOptionPowerDraft = $state<number | undefined>(undefined);
  let newFieldTargetBp = $state('');
  let newFieldMin = $state(0);
  let newFieldMax = $state(1000);
  let newFieldStep = $state(1);
  let newFieldUnit = $state('');
  let newFieldDefault = $state('');
  let newFieldFormula = $state('');

  // Inline option adder state for existing fields (keyed by field.id)
  let inlineNewOptionLabels = $state<Record<string, string>>({});
  let inlineNewOptionPowers = $state<Record<string, number | undefined>>({});

  // Sandbox simulation test state
  let testSandboxContext = $state<Record<string, any>>({
    'cultivation.major_realm': 3,
    'cultivation.minor_realm': 5,
    special_Physique: 2.0,
    attack: 1200,
    attack_technique_Mastery: 1.8,
    defence: 800,
    defence_technique_mastery: 1.2,
  });

  const fieldTypeOptions = [
    { value: 'STRING', label: 'Text (String)' },
    { value: 'NUMBER', label: 'Number (Numeric with bounds)' },
    { value: 'ENUM', label: 'Enum / Custom Categories (Options with Power/Value)' },
    { value: 'BLUEPRINT_REF', label: 'Blueprint Reference (1st or 2nd Class)' },
    { value: 'FORMULA', label: 'Formula (Mathematical & Logical Computed Math)' },
    { value: 'BOOLEAN', label: 'Toggle (Boolean)' },
  ];

  let availableTargetBlueprints = $derived(
    worldStore.blueprints.map((bp) => ({
      value: bp.id,
      label: `${bp.name} (${bp.blueprintClass === 'FIRST_CLASS' ? '1st Class' : '2nd Class'} · ${bp.category})`,
    }))
  );

  $effect(() => {
    if (blueprint) {
      name = blueprint.name;
      blueprintClass = blueprint.blueprintClass;
      category = blueprint.category;
      description = blueprint.description || '';
      if (!newFieldTargetBp && availableTargetBlueprints.length > 0) {
        newFieldTargetBp = availableTargetBlueprints[0].value;
      }
    }
  });

  function handleSaveBlueprintOverview() {
    if (!blueprint || !name.trim()) return;

    worldStore.updateBlueprint(blueprint.id, {
      name: name.trim(),
      blueprintClass,
      category: category.trim() || 'General',
      description: description.trim(),
    });

    saveMessage = 'Blueprint details successfully updated!';
    setTimeout(() => {
      saveMessage = null;
    }, 3000);
  }

  function handleAddNewField() {
    if (!blueprint) return;
    const key = (newFieldName.trim() || newFieldLabel.trim().toLowerCase().replace(/\s+/g, '_')).replace(/[^a-zA-Z0-9_\.]/g, '');
    if (!key) {
      alert('Field Key or Label is required.');
      return;
    }

    const fieldDef: Omit<DynamicFieldDef, 'id'> = {
      name: key,
      label: newFieldLabel.trim() || key,
      fieldType: newFieldType,
      description: newFieldDesc.trim(),
    };

    if (newFieldType === 'ENUM') {
      fieldDef.options = newFieldOptions.length > 0
        ? newFieldOptions.map((o) => ({ ...o }))
        : [{ label: 'Default', value: 'default', power: 0, numericValue: 0 }];
      fieldDef.defaultValue = newFieldDefault || (typeof fieldDef.options[0] === 'object' ? fieldDef.options[0].value : fieldDef.options[0]);
    } else if (newFieldType === 'NUMBER') {
      fieldDef.min = newFieldMin;
      fieldDef.max = newFieldMax;
      fieldDef.step = newFieldStep;
      fieldDef.unit = newFieldUnit;
      fieldDef.defaultValue = parseFloat(newFieldDefault) || 0;
    } else if (newFieldType === 'BLUEPRINT_REF') {
      fieldDef.targetBlueprintId = newFieldTargetBp;
      const targetBp = worldStore.getBlueprint(newFieldTargetBp);
      fieldDef.targetBlueprintName = targetBp?.name;
    } else if (newFieldType === 'FORMULA') {
      fieldDef.formulaExpression = newFieldFormula.trim();
      fieldDef.formulaDependencies = extractFormulaVariables(newFieldFormula);
    } else if (newFieldType === 'BOOLEAN') {
      fieldDef.defaultValue = newFieldDefault === 'true';
    } else {
      fieldDef.defaultValue = newFieldDefault;
    }

    worldStore.addFieldToBlueprint(blueprint.id, fieldDef);

    // Reset draft
    newFieldName = '';
    newFieldLabel = '';
    newFieldDesc = '';
    newFieldFormula = '';
    newFieldOptions = [
      { label: 'Option A', value: 'option_a', power: 100, numericValue: 100 },
      { label: 'Option B', value: 'option_b', power: 500, numericValue: 500 },
    ];
    newOptionLabelDraft = '';
    newOptionPowerDraft = undefined;
    showNewFieldModal = false;

    saveMessage = `Dynamic field "${key}" added to blueprint!`;
    setTimeout(() => {
      saveMessage = null;
    }, 3000);
  }

  function handleAddOptionToExistingField(fieldId: string) {
    if (!blueprint) return;
    const label = (inlineNewOptionLabels[fieldId] || '').trim();
    if (!label) return;
    const power = inlineNewOptionPowers[fieldId];
    const value = label.toLowerCase().replace(/\s+/g, '_');

    worldStore.addOptionToField(blueprint.id, fieldId, {
      label,
      value,
      power: power !== undefined ? Number(power) : 0,
      numericValue: power !== undefined ? Number(power) : 0,
    });

    inlineNewOptionLabels[fieldId] = '';
    inlineNewOptionPowers[fieldId] = undefined;
  }

  function handleRemoveOptionFromExistingField(fieldId: string, optionIndex: number) {
    if (!blueprint) return;
    worldStore.removeOptionFromField(blueprint.id, fieldId, optionIndex);
  }

  function handleDeleteField(fieldId: string, fieldName: string) {
    if (!blueprint) return;
    if (confirm(`Remove field "${fieldName}" from blueprint "${blueprint.name}"?`)) {
      worldStore.deleteBlueprintField(blueprint.id, fieldId);
    }
  }

  function handleDeleteBlueprint() {
    if (!blueprint) return;
    if (confirm(`Are you sure you want to permanently delete blueprint "${blueprint.name}"?`)) {
      worldStore.deleteBlueprint(blueprint.id);
      goto('/world/schemas');
    }
  }
</script>

{#if !blueprint}
  <div class="max-w-4xl mx-auto space-y-6">
    <Breadcrumb
      items={[
        { label: 'World Studio', href: '/world' },
        { label: 'Blueprints', href: '/world/schemas' },
        { label: 'Blueprint Not Found' },
      ]}
    />
    <div class="bg-zinc-900 rounded-lg border border-zinc-800 p-12 text-center space-y-3">
      <Shield class="w-8 h-8 text-zinc-600 mx-auto" />
      <h2 class="text-base font-bold text-zinc-300">Blueprint Not Found</h2>
      <a href="/world/schemas">
        <Button variant="outline" size="sm">Return to Blueprints Workbench</Button>
      </a>
    </div>
  </div>
{:else}
  <div class="max-w-4xl mx-auto space-y-6 pb-16">
    <!-- Breadcrumb -->
    <Breadcrumb
      items={[
        { label: 'World Studio', href: '/world' },
        { label: 'Blueprints & Schemas', href: '/world/schemas' },
        { label: blueprint.name },
      ]}
    />

    <!-- Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-zinc-800 pb-4">
      <div class="space-y-1">
        <div class="flex items-center gap-2">
          {#if blueprint.blueprintClass === 'FIRST_CLASS'}
            <Boxes class="w-5 h-5 text-teal-400" />
          {:else}
            <Layers class="w-5 h-5 text-cyan-400" />
          {/if}
          <h2 class="text-xl font-bold tracking-tight text-zinc-100">{blueprint.name}</h2>
        </div>
        <div class="flex items-center gap-2 text-xs">
          <span class={`font-medium ${blueprint.blueprintClass === 'FIRST_CLASS' ? 'text-teal-400' : 'text-cyan-400'}`}>
            {blueprint.blueprintClass === 'FIRST_CLASS' ? '1st-Class Entity Archetype' : '2nd-Class Sub-Schema'}
          </span>
          <span class="text-zinc-600">·</span>
          <span class="text-zinc-400 font-mono">{blueprint.id}</span>
        </div>
      </div>

      <div class="flex items-center gap-2">
        {#if blueprint.blueprintClass === 'FIRST_CLASS'}
          <a href={`/world/entities/create?blueprintId=${blueprint.id}`}>
            <Button variant="secondary" size="sm">
              <Plus class="w-3.5 h-3.5" />
              <span>Instantiate Entity</span>
            </Button>
          </a>
        {/if}
        <a href="/world/schemas">
          <Button variant="outline" size="sm">
            <ArrowLeft class="w-3.5 h-3.5" />
            <span>All Blueprints</span>
          </Button>
        </a>
      </div>
    </div>

    <!-- Notification Alert -->
    {#if saveMessage}
      <div class="p-3 bg-emerald-950/60 border border-emerald-800 rounded-lg text-xs text-emerald-300 flex items-center gap-2">
        <Check class="w-4 h-4 text-emerald-400 shrink-0" />
        <span>{saveMessage}</span>
      </div>
    {/if}

    <!-- Meta Details Card -->
    <div class="bg-zinc-900 rounded-lg border border-zinc-800 p-6 space-y-4">
      <h3 class="text-xs font-semibold text-zinc-300 uppercase tracking-wider flex items-center gap-2">
        <Boxes class="w-4 h-4 text-teal-400" />
        <span>Blueprint Identity & Metadata</span>
      </h3>

      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Field id="bp-name" label="Blueprint Name">
          <Input id="bp-name" bind:value={name} class="w-full text-xs" />
        </Field>

        <Field id="bp-cat" label="Category">
          <Input id="bp-cat" bind:value={category} class="w-full text-xs" />
        </Field>

        <Field id="bp-tier" label="Blueprint Tier">
          <Select
            id="bp-tier"
            bind:value={blueprintClass}
            options={[
              { value: 'FIRST_CLASS', label: '1st-Class Archetype' },
              { value: 'SECOND_CLASS', label: '2nd-Class Sub-Schema' },
            ]}
          />
        </Field>
      </div>

      <Field id="bp-desc" label="Description">
        <Textarea
          id="bp-desc"
          bind:value={description}
          rows={2}
          class="w-full text-xs"
        />
      </Field>

      <div class="flex justify-end pt-2">
        <Button variant="default" size="sm" onclick={handleSaveBlueprintOverview}>
          <Check class="w-3.5 h-3.5" />
          <span>Save Changes</span>
        </Button>
      </div>
    </div>

    <!-- Fields & Mathematical Formulas Workbench -->
    <div class="bg-zinc-900 rounded-lg border border-zinc-800 p-6 space-y-6">
      <div class="flex items-center justify-between border-b border-zinc-800 pb-3">
        <div>
          <h3 class="text-xs font-semibold text-zinc-300 uppercase tracking-wider flex items-center gap-2">
            <Sparkles class="w-4 h-4 text-teal-400" />
            <span>Defined Fields & Mathematical Formulas ({blueprint.fields.length})</span>
          </h3>
          <p class="text-xs text-zinc-500 mt-0.5">
            Manage custom field schemas, enum options, target blueprint references, and computed formulas.
          </p>
        </div>

        <Button variant="secondary" size="sm" onclick={() => (showNewFieldModal = !showNewFieldModal)}>
          <Plus class="w-3.5 h-3.5" />
          <span>{showNewFieldModal ? 'Close Form' : 'Attach New Field'}</span>
        </Button>
      </div>

      <!-- Add New Field Form Drawer -->
      {#if showNewFieldModal}
        <div class="p-5 rounded-lg border border-teal-800/60 bg-teal-950/20 space-y-4">
          <div class="flex items-center gap-2 text-xs font-semibold text-teal-300">
            <Plus class="w-4 h-4 text-teal-400" />
            <span>Add New Dynamic Field to Blueprint</span>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <span class="block text-[11px] font-medium text-zinc-400 mb-1">Field Machine Key</span>
              <Input
                bind:value={newFieldName}
                placeholder="e.g. gender, attack, total_power"
                class="font-mono text-xs w-full"
              />
            </div>

            <div>
              <span class="block text-[11px] font-medium text-zinc-400 mb-1">Display Label</span>
              <Input
                bind:value={newFieldLabel}
                placeholder="e.g. Gender, Attack Power"
                class="text-xs w-full"
              />
            </div>

            <div>
              <span class="block text-[11px] font-medium text-zinc-400 mb-1">Field Type</span>
              <Select bind:value={newFieldType} options={fieldTypeOptions} />
            </div>
          </div>

          <!-- ENUM options builder -->
          {#if newFieldType === 'ENUM'}
            <div class="p-3 bg-zinc-900 rounded border border-zinc-800 space-y-3">
              <div class="flex items-center justify-between">
                <span class="text-xs font-semibold text-teal-400">Enum Options & Dual-Valued Power Metrics</span>
                <span class="text-[10px] text-zinc-500">Attach numeric values for mathematical formulas</span>
              </div>
              <div class="flex flex-wrap gap-1.5">
                {#each newFieldOptions as opt, optIdx}
                  <span class="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-zinc-800 border border-zinc-700 text-xs text-zinc-200">
                    <span>{opt.label}</span>
                    {#if opt.power !== undefined || opt.numericValue !== undefined}
                      <span class="px-1 py-0.2 rounded bg-teal-950 text-teal-300 font-mono text-[10px]">
                        Power: {opt.power ?? opt.numericValue}
                      </span>
                    {/if}
                    <button
                      type="button"
                      onclick={() => newFieldOptions.splice(optIdx, 1)}
                      class="text-zinc-400 hover:text-red-400 ml-0.5"
                    >
                      &times;
                    </button>
                  </span>
                {/each}
              </div>
              <div class="grid grid-cols-1 sm:grid-cols-3 gap-2 items-center">
                <Input
                  bind:value={newOptionLabelDraft}
                  placeholder="Option Name (e.g. Golden Core)"
                  class="text-xs sm:col-span-1"
                  onkeydown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      if (newOptionLabelDraft.trim()) {
                        const lbl = newOptionLabelDraft.trim();
                        const pwr = newOptionPowerDraft !== undefined ? Number(newOptionPowerDraft) : 0;
                        newFieldOptions.push({
                          label: lbl,
                          value: lbl.toLowerCase().replace(/\s+/g, '_'),
                          power: pwr,
                          numericValue: pwr,
                        });
                        newOptionLabelDraft = '';
                        newOptionPowerDraft = undefined;
                      }
                    }
                  }}
                />
                <Input
                  type="number"
                  bind:value={newOptionPowerDraft}
                  placeholder="Power / Value (e.g. 500)"
                  class="text-xs font-mono sm:col-span-1"
                />
                <Button
                  variant="secondary"
                  size="sm"
                  class="sm:col-span-1"
                  onclick={() => {
                    if (newOptionLabelDraft.trim()) {
                      const lbl = newOptionLabelDraft.trim();
                      const pwr = newOptionPowerDraft !== undefined ? Number(newOptionPowerDraft) : 0;
                      newFieldOptions.push({
                        label: lbl,
                        value: lbl.toLowerCase().replace(/\s+/g, '_'),
                        power: pwr,
                        numericValue: pwr,
                      });
                      newOptionLabelDraft = '';
                      newOptionPowerDraft = undefined;
                    }
                  }}
                >
                  <Plus class="w-3.5 h-3.5" />
                  <span>Add Option</span>
                </Button>
              </div>
            </div>
          {/if}

          <!-- Blueprint Ref -->
          {#if newFieldType === 'BLUEPRINT_REF'}
            <div class="p-3 bg-zinc-900 rounded border border-zinc-800 space-y-2">
              <span class="text-xs font-medium text-cyan-400">Target Blueprint</span>
              <Select bind:value={newFieldTargetBp} options={availableTargetBlueprints} />
            </div>
          {/if}

          <!-- Formula -->
          {#if newFieldType === 'FORMULA'}
            <div class="p-3.5 bg-zinc-900 rounded border border-amber-900/50 space-y-2">
              <span class="text-xs font-medium text-amber-400">Mathematical Formula Expression</span>
              <Input
                bind:value={newFieldFormula}
                placeholder="(cultivation.major_realm * cultivation.minor_realm) * special_Physique + attack * attack_technique_Mastery - defence * defence_technique_mastery"
                class="font-mono text-xs w-full bg-black/60 border-amber-900/60"
              />
              <div class="flex flex-wrap gap-1">
                {#each blueprint.fields.map((f) => f.name) as fKey}
                  <button
                    type="button"
                    onclick={() => (newFieldFormula = newFieldFormula ? `${newFieldFormula} ${fKey}` : fKey)}
                    class="text-[10px] font-mono px-2 py-0.5 rounded bg-zinc-800 text-amber-300 hover:bg-zinc-700 transition"
                  >
                    {fKey}
                  </button>
                {/each}
              </div>
            </div>
          {/if}

          <div class="flex justify-end gap-2 pt-2">
            <Button variant="outline" size="sm" onclick={() => (showNewFieldModal = false)}>Cancel</Button>
            <Button variant="default" size="sm" onclick={handleAddNewField}>
              <Check class="w-3.5 h-3.5" />
              <span>Attach Field</span>
            </Button>
          </div>
        </div>
      {/if}

      <!-- Current Blueprint Fields List -->
      <div class="space-y-3">
        {#each blueprint.fields as field (field.id)}
          <div class="p-4 rounded-lg border border-zinc-800 bg-zinc-950/50 space-y-2.5">
            <div class="flex items-start justify-between">
              <div class="space-y-1">
                <div class="flex items-center gap-2">
                  {#if field.fieldType === 'FORMULA'}
                    <Calculator class="w-4 h-4 text-amber-400" />
                  {:else if field.fieldType === 'ENUM'}
                    <ListFilter class="w-4 h-4 text-teal-400" />
                  {:else if field.fieldType === 'BLUEPRINT_REF'}
                    <Link2 class="w-4 h-4 text-cyan-400" />
                  {:else if field.fieldType === 'NUMBER'}
                    <Hash class="w-4 h-4 text-emerald-400" />
                  {:else}
                    <Boxes class="w-4 h-4 text-zinc-400" />
                  {/if}
                  <span class="text-sm font-semibold text-zinc-100">{field.label}</span>
                  <span class="text-xs font-mono text-zinc-500">({field.name})</span>
                </div>
                {#if field.description}
                  <p class="text-xs text-zinc-400">{field.description}</p>
                {/if}
              </div>

              <div class="flex items-center gap-3">
                <span class="text-[11px] font-mono px-2 py-0.5 rounded bg-zinc-900 border border-zinc-800 text-zinc-300">
                  {field.fieldType}
                </span>
                <button
                  type="button"
                  onclick={() => handleDeleteField(field.id, field.name)}
                  class="text-zinc-600 hover:text-red-400 p-1 transition"
                  title="Remove Field"
                >
                  <Trash2 class="w-3.5 h-3.5" />
                </button>
              </div>
            </div>

            <!-- Enum Details & Options Management -->
            {#if field.fieldType === 'ENUM' && field.options}
              <div class="space-y-2 pt-2 border-t border-zinc-900">
                <div class="flex items-center justify-between text-xs">
                  <span class="text-zinc-400 font-medium">Enum Options & Formula Power Values:</span>
                  <span class="text-[10px] text-zinc-500 font-mono">{field.options.length} options defined</span>
                </div>

                <div class="flex flex-wrap gap-1.5">
                  {#each field.options as opt, optIdx}
                    {@const optLabel = typeof opt === 'string' ? opt : opt.label}
                    {@const optPower = typeof opt === 'string' ? undefined : (opt.power ?? opt.numericValue)}
                    <span class="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-zinc-900 border border-zinc-800 text-[11px] text-zinc-300">
                      <span>{optLabel}</span>
                      {#if optPower !== undefined}
                        <span class="px-1 py-0.2 rounded bg-teal-950/80 text-teal-300 font-mono text-[10px]">
                          Power: {optPower}
                        </span>
                      {/if}
                      <button
                        type="button"
                        onclick={() => handleRemoveOptionFromExistingField(field.id, optIdx)}
                        class="text-zinc-500 hover:text-red-400 transition ml-0.5"
                        title="Delete Option"
                      >
                        &times;
                      </button>
                    </span>
                  {/each}
                </div>

                <!-- Inline Option Adder -->
                <div class="flex items-center gap-2 max-w-md pt-1">
                  <Input
                    bind:value={inlineNewOptionLabels[field.id]}
                    placeholder="New Option (e.g. Tribulation Realm)"
                    class="text-xs h-7"
                    onkeydown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        handleAddOptionToExistingField(field.id);
                      }
                    }}
                  />
                  <Input
                    type="number"
                    bind:value={inlineNewOptionPowers[field.id]}
                    placeholder="Power"
                    class="text-xs font-mono h-7 w-24"
                    onkeydown={(e) => {
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        handleAddOptionToExistingField(field.id);
                      }
                    }}
                  />
                  <Button
                    variant="secondary"
                    size="sm"
                    class="h-7 px-2.5 text-xs shrink-0"
                    onclick={() => handleAddOptionToExistingField(field.id)}
                  >
                    <Plus class="w-3 h-3" />
                    <span>Add</span>
                  </Button>
                </div>
              </div>
            {/if}

            <!-- Blueprint Ref Details -->
            {#if field.fieldType === 'BLUEPRINT_REF'}
              <div class="flex items-center gap-2 text-xs pt-1 text-cyan-400 font-medium">
                <Link2 class="w-3.5 h-3.5" />
                <span>Referenced Blueprint: {field.targetBlueprintName || field.targetBlueprintId}</span>
              </div>
            {/if}

            <!-- Formula Details & Live Evaluation preview -->
            {#if field.fieldType === 'FORMULA' && field.formulaExpression}
              {@const evalRes = evaluateFormula(field.formulaExpression, testSandboxContext)}
              <div class="p-3 bg-zinc-900 rounded border border-amber-950/60 space-y-2 mt-2">
                <div class="flex items-center justify-between text-xs">
                  <div class="flex items-center gap-1.5 text-amber-400 font-mono">
                    <Calculator class="w-3.5 h-3.5" />
                    <span>Formula: {field.formulaExpression}</span>
                  </div>
                  {#if evalRes.success}
                    <div class="inline-flex items-center gap-1 text-emerald-400 font-bold font-mono">
                      <span>Evaluated Result: {evalRes.formattedValue}</span>
                    </div>
                  {/if}
                </div>
              </div>
            {/if}
          </div>
        {/each}
      </div>
    </div>

    <!-- Danger Zone -->
    <div class="bg-zinc-900 rounded-lg border border-red-950/40 p-5 flex items-center justify-between">
      <div>
        <h4 class="text-xs font-bold text-red-400 uppercase tracking-wider">Delete Blueprint</h4>
        <p class="text-xs text-zinc-500 mt-0.5">
          Permanently remove this blueprint from the world schema registry.
        </p>
      </div>
      <Button variant="outline" size="sm" onclick={handleDeleteBlueprint} class="text-red-400 hover:bg-red-950/50 hover:border-red-800">
        <Trash2 class="w-3.5 h-3.5" />
        <span>Delete Blueprint</span>
      </Button>
    </div>
  </div>
{/if}
