// apps/mobile/src/components/Pagination.tsx
/**
 * @file Pagination.tsx
 * @description Mobile adaptation of apps/web/src/lib/components/ui/pagination.svelte
 */

import React from "react";
import { View, Text, TouchableOpacity } from "react-native";
import { ChevronLeft, ChevronRight } from "lucide-react-native";

interface PaginationProps {
  page?: number;
  currentPage?: number;
  pageSize?: number;
  totalCount?: number;
  totalItems?: number;
  totalPages?: number;
  itemLabel?: string;
  onPageChange: (newPage: number) => void;
}

export function Pagination({
  page: propPage,
  currentPage: propCurrentPage,
  pageSize = 10,
  totalCount: propTotalCount,
  totalItems: propTotalItems,
  totalPages: propTotalPages,
  itemLabel = "items",
  onPageChange,
}: PaginationProps) {
  const page = propCurrentPage ?? propPage ?? 1;
  const totalCount = propTotalItems ?? propTotalCount ?? 0;
  const totalPages =
    propTotalPages !== undefined
      ? propTotalPages
      : Math.max(1, Math.ceil(totalCount / pageSize));
  const hasNextPage = page < totalPages;
  const hasPreviousPage = page > 1;

  const startItem = totalCount === 0 ? 0 : (page - 1) * pageSize + 1;
  const endItem = Math.min(totalCount, page * pageSize);

  return (
    <View
      style={{
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: "rgba(18, 18, 21, 0.8)",
        borderBottomWidth: 1,
        borderBottomColor: "#27272a",
        flexWrap: "wrap",
        gap: 8,
      }}
    >
      <Text style={{ color: "#a1a1aa", fontSize: 11, fontFamily: "monospace" }}>
        {totalCount === 0
          ? `0 ${itemLabel}`
          : `Showing ${startItem}–${endItem} of ${totalCount} ${itemLabel}`}
      </Text>

      <View style={{ flexDirection: "row", alignItems: "center", gap: 6 }}>
        <TouchableOpacity
          disabled={!hasPreviousPage}
          onPress={() => onPageChange(page - 1)}
          style={{
            flexDirection: "row",
            alignItems: "center",
            gap: 2,
            backgroundColor: "#1e1e24",
            borderColor: "#27272a",
            borderWidth: 1,
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
            opacity: hasPreviousPage ? 1 : 0.4,
            minHeight: 32,
          }}
        >
          <ChevronLeft size={14} color="#fafafa" />
          <Text style={{ color: "#fafafa", fontSize: 11, fontWeight: "600" }}>
            Prev
          </Text>
        </TouchableOpacity>

        <View
          style={{
            backgroundColor: "#121215",
            borderColor: "#27272a",
            borderWidth: 1,
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
            minHeight: 32,
            justifyContent: "center",
          }}
        >
          <Text
            style={{ color: "#a1a1aa", fontSize: 11, fontFamily: "monospace" }}
          >
            {page} / {totalPages}
          </Text>
        </View>

        <TouchableOpacity
          disabled={!hasNextPage}
          onPress={() => onPageChange(page + 1)}
          style={{
            flexDirection: "row",
            alignItems: "center",
            gap: 2,
            backgroundColor: "#1e1e24",
            borderColor: "#27272a",
            borderWidth: 1,
            paddingHorizontal: 8,
            paddingVertical: 4,
            borderRadius: 6,
            opacity: hasNextPage ? 1 : 0.4,
            minHeight: 32,
          }}
        >
          <Text style={{ color: "#fafafa", fontSize: 11, fontWeight: "600" }}>
            Next
          </Text>
          <ChevronRight size={14} color="#fafafa" />
        </TouchableOpacity>
      </View>
    </View>
  );
}

// apps/web/src/lib/components/ui/pagination.svelte
<script lang="ts">
  import { ChevronLeft, ChevronRight } from 'lucide-svelte';
  import { Button } from '$lib/components/ui';

  interface Props {
    page: number;
    pageSize?: number;
    totalCount: number;
    totalPages?: number;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;
    itemLabel?: string;
    class?: string;
    onPageChange: (newPage: number) => void;
  }

  let {
    page = 1,
    pageSize = 10,
    totalCount = 0,
    totalPages: propTotalPages,
    hasNextPage: propHasNextPage,
    hasPreviousPage: propHasPreviousPage,
    itemLabel = 'items',
    class: className = '',
    onPageChange,
  }: Props = $props();

  const totalPages = $derived(
    propTotalPages !== undefined ? propTotalPages : Math.max(1, Math.ceil(totalCount / pageSize))
  );

  const hasNextPage = $derived(
    propHasNextPage !== undefined ? propHasNextPage : page < totalPages
  );

  const hasPreviousPage = $derived(
    propHasPreviousPage !== undefined ? propHasPreviousPage : page > 1
  );

  const startItem = $derived(totalCount === 0 ? 0 : (page - 1) * pageSize + 1);
  const endItem = $derived(Math.min(totalCount, page * pageSize));

  function handlePrevious() {
    if (hasPreviousPage && page > 1) {
      onPageChange(page - 1);
    }
  }

  function handleNext() {
    if (hasNextPage && page < totalPages) {
      onPageChange(page + 1);
    }
  }
</script>

<div class={`flex flex-col sm:flex-row items-center justify-between gap-3 px-4 py-3 border-t border-border bg-card/40 ${className}`}>
  <!-- Item Range Telemetry -->
  <div class="text-xs text-muted-foreground font-mono">
    {#if totalCount === 0}
      <span>0 {itemLabel}</span>
    {:else}
      <span>Showing <strong class="text-foreground font-semibold">{startItem}</strong>–<strong class="text-foreground font-semibold">{endItem}</strong> of <strong class="text-foreground font-semibold">{totalCount}</strong> {itemLabel}</span>
    {/if}
  </div>

  <!-- Pagination Buttons & Page Indicator -->
  <div class="flex items-center gap-2">
    <!-- Previous Page Button -->
    <Button
      variant="outline"
      size="sm"
      class="h-8 px-3 text-xs flex items-center gap-1.5 cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
      disabled={!hasPreviousPage || page <= 1}
      onclick={handlePrevious}
      aria-label="Previous Page"
    >
      <ChevronLeft class="w-3.5 h-3.5" />
      <span>Previous</span>
    </Button>

    <!-- Page Number Text -->
    <div class="px-2.5 py-1 rounded bg-muted/60 border border-border/70 text-xs font-mono text-muted-foreground min-w-[75px] text-center">
      Page <strong class="text-foreground">{page}</strong> / {totalPages}
    </div>

    <!-- Next Page Button -->
    <Button
      variant="outline"
      size="sm"
      class="h-8 px-3 text-xs flex items-center gap-1.5 cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
      disabled={!hasNextPage || page >= totalPages}
      onclick={handleNext}
      aria-label="Next Page"
    >
      <span>Next</span>
      <ChevronRight class="w-3.5 h-3.5" />
    </Button>
  </div>
</div>
